### ISSUE TITLE
Salesforce Initialization Error 

### ISSUE THREAD

**Issue by rich-hart** [openstax/openstax-cms#115]
Python 3.4 on Ubuntu 15.04 does not like how the subclass is referencing simple_salesforce methods.  I've ran this same test on in python 3.5 on OS X 10.11and it passes.

```.pytbc
Creating test database for alias 'default'...
E
======================================================================
ERROR: test_faculty_rejected (accounts.tests.SalesforceTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vagrant/development/openstax-cms/accounts/tests.py", line 111, in test_faculty_rejected
    status = sf.faculty_status(3)
  File "/home/vagrant/development/openstax-cms/accounts/salesforce.py", line 32, in faculty_status
    contact_info = self.query(sql_command)
  File "/home/vagrant/development/venv/lib/python3.4/site-packages/simple_salesforce/api.py", line 278, in query
    url = self.base_url + 'query/'
  File "/home/vagrant/development/venv/lib/python3.4/site-packages/simple_salesforce/api.py", line 167, in __getattr__
    return SFType(name, self.session_id, self.sf_instance, self.sf_version, self.proxies)

            *
            *
            *

  File "/home/vagrant/development/venv/lib/python3.4/site-packages/simple_salesforce/api.py", line 167, in __getattr__
    return SFType(name, self.session_id, self.sf_instance, self.sf_version, self.proxies)
RuntimeError: maximum recursion depth exceeded while calling a Python object

----------------------------------------------------------------------
Ran 1 test in 0.509s

FAILED (errors=1)
Destroying test database for alias 'default'...
```

**Comment by rich-hart** [comment]
Looks all it needed was some better error handling.  PR open for fix.

**Comment by rich-hart** [comment]
Python update to version 3.5 on Ubuntu 15.04:
```
add-apt-repository ppa:fkrull/deadsnakes
apt-get update
apt-get install python3.5
apt-get install python3.5-dev
```

**Comment by rich-hart** [comment]
Current error message:
```
======================================================================
ERROR: test_faculty_unknown (workspace.openstax-cms.accounts.tests.SalesforceTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/openstax/workspace/openstax-cms/accounts/salesforce.py", line 13, in __init__
    super(Salesforce, self).__init__(**settings.SALESFORCE)
  File "/Users/openstax/workspace/openstax-cms/venv/lib/python3.5/site-packages/django/conf/__init__.py", line 56, in __getattr__
    return getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'SALESFORCE'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/openstax/workspace/openstax-cms/accounts/tests.py", line 100, in test_faculty_unknown
    with Salesforce() as sf:
  File "/Users/openstax/workspace/openstax-cms/accounts/salesforce.py", line 15, in __init__
    super(Salesforce, self).__init__(*args,**kwargs)
  File "/Users/openstax/workspace/openstax-cms/venv/lib/python3.5/site-packages/simple_salesforce/api.py", line 112, in __init__
    'You must provide login information or an instance and token'
TypeError: You must provide login information or an instance and token
```
