### ISSUE TITLE
Logging Configuration

### ISSUE THREAD

**Issue by rich-hart** [openstax/openstax-cms#131]
``` .pytb

Traceback (most recent call last):
  File "/usr/lib/python3.4/logging/config.py", line 557, in configure
    handler = self.configure_handler(handlers[name])
  File "/usr/lib/python3.4/logging/config.py", line 725, in configure_handler
    result = factory(**kwargs)
  File "/usr/lib/python3.4/logging/__init__.py", line 1006, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.4/logging/__init__.py", line 1030, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: '/var/www/openstax-cms/server.log'
```

Current base logging configuration is not compatible with current dev environment.  Quick fix: `chmod 775 /var/www/openstax-cms/server.log`.

**Comment by rich-hart** [comment]
```.pytb

Traceback (most recent call last):
  File "/usr/lib/python3.4/logging/config.py", line 557, in configure
    handler = self.configure_handler(handlers[name])
  File "/usr/lib/python3.4/logging/config.py", line 725, in configure_handler
    result = factory(**kwargs)
  File "/usr/lib/python3.4/logging/__init__.py", line 1006, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.4/logging/__init__.py", line 1030, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: '/var/www/openstax-cms/server.log'
```
